kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: example
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          imagePullPolicy: Never
          image: example:1.0
          ports:
            - name: http
              containerPort: 3000
