kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: service-1
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          imagePullPolicy: Never
          image: example:1.0
          command: ["/app/bin/service.1"]
          ports:
            - name: http
              containerPort: 3000
