kind: Service
apiVersion: v1
metadata:
  name: service-1
spec:
  selector:
    app: service-1
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31001
#    - protocol: TCP
#      port: 3000
#      targetPort: http
#      nodePort: 31000
