kind: Service
apiVersion: v1
metadata:
  name: service-2
spec:
  selector:
    app: service-2
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31002
#    - protocol: TCP
#      port: 3000
#      targetPort: http
#      nodePort: 31000
